### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jason233333** [oceaneLIU/GraphCoder#3]
In `utils/ccg.py/create_graph`
![Snipaste_2024-09-13_10-11-19](https://github.com/user-attachments/assets/c11560ec-b4f3-4642-83c5-be7534015494)

`language` is a Class of tree_sitter, thus comment_prefix is always "".

**Comment by gameraroma** [comment]
I've changed as this code instead and it work; `if CONSTANTS.repos_language[repo_name] == "python":`

**Comment by GCVulnerability** [comment]
@gameraroma I have followed your change. But it seems to have a new error.

Traceback (most recent call last):
  File "G:\GraphCoder\build_graph_database.py", line 73, in <module>
    graph_db_builder.build_slicing_graph_database(repo)
  File "G:\GraphCoder\build_graph_database.py", line 36, in build_slicing_graph_database
    ccg = create_graph(src_lines, repo_name)
  File "G:\GraphCoder\utils\ccg.py", line 774, in create_graph
    last_node_id = node_list[-1]
IndexError: list index out of range

Do you succeed in generating CCF? If so, could you please share it?
